# Generated by Django 4.2.7 on 2024-04-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовка")),
                ("description", models.TextField(verbose_name="описание")),
                ("image", models.ImageField(upload_to="product", verbose_name="фото")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата созлание"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
