# Generated by Django 4.2.7 on 2024-07-01 08:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовка")),
                ("description", models.TextField(verbose_name="описание")),
                ("image", models.ImageField(upload_to="product", verbose_name="фото")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата созлание"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=100, verbose_name="Цена")),
                (
                    "extra_info",
                    ckeditor.fields.RichTextField(verbose_name="Описание продукта"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=155, verbose_name="имя")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("message", models.CharField(max_length=355, verbose_name="Сообщение")),
            ],
            options={
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="Send_Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name_plural": "Форма обратного связи",
            },
        ),
    ]
