# Generated by Django 4.2.7 on 2024-04-30 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=100, verbose_name="Цена")),
                (
                    "extra_info",
                    ckeditor.fields.RichTextField(verbose_name="Описание продукта"),
                ),
            ],
        ),
    ]
