# Generated by Django 4.2.7 on 2024-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_productdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=155, verbose_name="имя")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("message", models.CharField(max_length=355, verbose_name="Сообщение")),
            ],
            options={
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
