# Generated by Django 4.2.7 on 2024-04-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                (
                    "descriptions",
                    models.CharField(max_length=355, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="settings/", verbose_name="Фото"),
                ),
            ],
            options={
                "verbose_name_plural": "настройка",
            },
        ),
    ]
