# Generated by Django 4.2.7 on 2024-04-30 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_about"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
    ]
