# Generated by Django 4.2.7 on 2024-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_delete_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Send_Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name_plural": "Форма обратного связи",
            },
        ),
    ]
