# Generated by Django 4.2.7 on 2024-04-01 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Telegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_user",
                    models.CharField(
                        max_length=100, verbose_name="ID пользователя telegram"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Имя")),
                ("email", models.CharField(max_length=155, verbose_name="Почта")),
                ("message", models.CharField(max_length=155, verbose_name="Сообщение")),
                ("chat_id", models.CharField(max_length=100, verbose_name="Чат ID")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата регистрации",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Телеграм бот",
            },
        ),
    ]
