# Generated by Django 4.2.7 on 2024-04-28 13:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegram",
            name="message",
            field=ckeditor.fields.RichTextField(verbose_name="Сообщение"),
        ),
    ]
